name: 'Lint'

on: [push]

jobs:
  lint:
     runs-on: ubuntu-latest
     steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm ci
      
      - name: 'run eslint'
        run: npm run lint